# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e3903d5cc1693967f0ce62d1300e6db08a1213e8598e0c06c8c01c78d5b99b321b21440ceee5f61d3254e35b4c7d65b7cc583b3e60ed7013f5aaa190b848f6f1

test:
  secret_key_base: c450c01f94c91b18980fad8495429c5e1654bd06c6ceb057487d08dc5e7f28cfa2460a061a3158904be0177c5363507a2600678030c546e7ea3d3bccb63092a3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
